"""
EventEngine 类型化事件载荷（Phase 3）

定义策略层事件的数据类：
- :class:`Event`       — 通用 key-value 事件（兼容现有 signal_bus）
- :class:`BarEvent`    — 完成的 K 线 bar
- :class:`TickEvent`   — 实时行情 tick
- :class:`OrderEvent`  — 订单生命周期（提交/成交/撤销）
- :class:`SignalEvent` — 策略生成的交易信号

不依赖 Qt、xtquant 或任何 GUI 模块，可在任意线程中安全构造。
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class Event:
    """General-purpose event compatible with the existing :class:`~core.signal_bus.SignalBus`.

    ``type`` 对应 :class:`~core.events.Events` 中的字符串常量；
    ``data`` 携带任意键值载荷。
    """

    type: str
    data: dict[str, Any] = field(default_factory=dict)


@dataclass
class BarEvent:
    """One completed K-line bar pushed by the realtime pipeline or data loader."""

    type: str = "bar"
    symbol: str = ""
    period: str = ""        # '1m', '5m', '15m', '1d', ...
    time: str = ""          # ISO-format datetime string
    open: float = 0.0       # noqa: A003  (shadows builtin 'open' only for this field)
    high: float = 0.0
    low: float = 0.0
    close: float = 0.0
    volume: float = 0.0
    adjust: str = "none"    # 'pre' | 'post' | 'none'


@dataclass
class TickEvent:
    """Real-time quote tick from any data source."""

    type: str = "tick"
    symbol: str = ""
    price: float = 0.0
    volume: float = 0.0
    amount: float = 0.0
    bid: float = 0.0
    ask: float = 0.0
    time: str = ""


@dataclass
class OrderEvent:
    """Order lifecycle event: submitted → filled / partial / cancelled."""

    type: str = "order"
    order_id: str = ""
    symbol: str = ""
    direction: str = ""     # 'buy' | 'sell'
    price: float = 0.0
    volume: float = 0.0
    filled_volume: float = 0.0
    status: str = ""        # 'submitted' | 'filled' | 'partial' | 'cancelled'
    time: str = ""


@dataclass
class SignalEvent:
    """Trading signal generated by a strategy."""

    type: str = "signal"
    strategy_id: str = ""
    symbol: str = ""
    direction: str = ""     # 'buy' | 'sell' | 'flat'
    price: float = 0.0
    time: str = ""
    meta: dict[str, Any] = field(default_factory=dict)
